module VerifyExamples.Atoms.Get0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Atoms exposing (..)



calcium : PeriodicTableInfo
calcium = get Ca periodicTable



spec0 : Test.Test
spec0 =
    Test.test "#get: \n\n    calcium.group\n    --> 2" <|
        \() ->
            Expect.equal
                (
                calcium.group
                )
                (
                2
                )