module VerifyExamples.Atoms.Get1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Atoms exposing (..)



calcium : PeriodicTableInfo
calcium = get Ca periodicTable



spec1 : Test.Test
spec1 =
    Test.test "#get: \n\n    calcium.period\n    --> 4" <|
        \() ->
            Expect.equal
                (
                calcium.period
                )
                (
                4
                )