module VerifyExamples.Atoms.ModuleDoc1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Atoms exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "Module VerifyExamples: \n\n    periodicTable.hydrogen.atomicNumber\n    --> 1" <|
        \() ->
            Expect.equal
                (
                periodicTable.hydrogen.atomicNumber
                )
                (
                1
                )