module VerifyExamples.Atoms.ModuleDoc0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Atoms exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "Module VerifyExamples: \n\n    periodicTable.carbon.atomicNumber\n    --> 6" <|
        \() ->
            Expect.equal
                (
                periodicTable.carbon.atomicNumber
                )
                (
                6
                )